// P4a acceptance tests: the S1 sign-off list made permanent. Every ACCEPTED
// semantic from docs/v2-s1-metadata-findings.md §4 is asserted against the
// S1 corpus (generated by testdata/gen_corpus.py, ground truth in
// testdata/manifest.json, v1 reference values in testdata/gold_v1.json from
// music-metadata@11.14.0).

package audio

import (
	"math"
	"path/filepath"
	"testing"
)

// corpusFile is one row of the parity table: the full v1-equivalent schema
// for one corpus file. Zero/nil means "absent" (v1 `?? undefined`).
type corpusFile struct {
	name string

	title        string
	artist       string
	artists      []string
	album        string
	albumArtist  string
	albumArtists []string
	trackNo      int
	trackTotal   int
	discNo       int
	discTotal    int
	year         int
	date         string
	genres       []string
	composers    []string
	producers    []string
	labels       []string
	releaseType  string
	comment      string
	bpm          int

	mbidRecording    string
	mbidRelease      string
	mbidReleaseGroup string
	mbidAlbumArtist  string
	mbidArtistIDs    []string

	barcode string
	asin    string
	isrcs   []string

	replayGainTrack float64
	replayGainAlbum float64

	explicit    *bool
	compilation *bool

	lyrics       string
	syncedLyrics []SyncedLyricLine

	hasCoverArt bool
	pictureMime string
	pictureSize int

	duration      float64 // gold_v1.json format.duration
	bitrate       int     // gold format.bitrate (m4a: see tolerance note)
	sampleRate    int
	channels      int
	bitsPerSample int
}

var spikeSynced = []SyncedLyricLine{
	{Time: 0, Text: "Synced line one"},
	{Time: 1.5, Text: "Synced line two"},
}

// spikeFiles carry the full v1 tag schema (identical across mp3/flac/ogg/m4a;
// m4a adds compilation+producer, mp3 drops producers per W3 parity).
var spikeFiles = []corpusFile{
	{
		name:             "spike.mp3",
		title:            "Spike Song (feat. Test)",
		artist:           "Spike Artist One",
		artists:          []string{"Spike Artist One", "Spike Artist Two"},
		album:            "Spike Album",
		albumArtist:      "Spike Album Artist",
		albumArtists:     []string{"Spike Album Artist"},
		trackNo:          3,
		trackTotal:       12,
		discNo:           1,
		discTotal:        2,
		year:             2021,
		date:             "2021-05-04",
		genres:           []string{"Jazz", "Fusion"},
		composers:        []string{"Spike Composer One", "Spike Composer Two"},
		labels:           []string{"Spike Label"},
		releaseType:      "soundtrack", // v1 preference rule: "album; soundtrack" → soundtrack
		comment:          "Spike comment text",
		bpm:              128,
		mbidRecording:    "11111111-2222-3333-4444-555555555555",
		mbidRelease:      "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
		mbidReleaseGroup: "dddddddd-1111-2222-3333-444444444444",
		mbidAlbumArtist:  "cccccccc-1111-2222-3333-444444444444",
		mbidArtistIDs: []string{
			"aaaaaaaa-1111-2222-3333-444444444444",
			"bbbbbbbb-1111-2222-3333-444444444444",
		},
		barcode:         "1234567890123",
		asin:            "B0C0SPIKE0",
		isrcs:           []string{"USS1O210001"},
		replayGainTrack: -7.03,
		replayGainAlbum: -6.51,
		explicit:        boolPtr(true),
		lyrics:          "Plain lyrics line one\nPlain lyrics line two",
		syncedLyrics:    spikeSynced,
		hasCoverArt:     true,
		pictureMime:     "image/png",
		pictureSize:     70,
		duration:        3.1346938775510202,
		bitrate:         128000,
		sampleRate:      44100,
		channels:        2,
	},
	{
		name:             "spike.flac",
		title:            "Spike Song (feat. Test)",
		artist:           "Spike Artist One",
		artists:          []string{"Spike Artist One", "Spike Artist Two"},
		album:            "Spike Album",
		albumArtist:      "Spike Album Artist",
		albumArtists:     []string{"Spike Album Artist"},
		trackNo:          3,
		trackTotal:       12,
		discNo:           1,
		discTotal:        2,
		year:             2021,
		date:             "2021-05-04",
		genres:           []string{"Jazz", "Fusion"},
		composers:        []string{"Spike Composer One", "Spike Composer Two"},
		producers:        []string{"Spike Producer"},
		labels:           []string{"Spike Label"},
		releaseType:      "soundtrack",
		comment:          "Spike comment text",
		bpm:              128,
		mbidRecording:    "11111111-2222-3333-4444-555555555555",
		mbidRelease:      "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
		mbidReleaseGroup: "dddddddd-1111-2222-3333-444444444444",
		mbidAlbumArtist:  "cccccccc-1111-2222-3333-444444444444",
		mbidArtistIDs: []string{
			"aaaaaaaa-1111-2222-3333-444444444444",
			"bbbbbbbb-1111-2222-3333-444444444444",
		},
		barcode:         "1234567890123",
		asin:            "B0C0SPIKE0",
		isrcs:           []string{"USS1O210001"},
		replayGainTrack: -7.03,
		replayGainAlbum: -6.51,
		explicit:        boolPtr(true),
		lyrics:          "Plain lyrics line one\nPlain lyrics line two",
		syncedLyrics:    spikeSynced,
		hasCoverArt:     true,
		pictureMime:     "image/png",
		pictureSize:     70,
		duration:        3,
		bitrate:         0, // v1 parity: music-metadata reports 0 for FLAC
		sampleRate:      44100,
		channels:        2,
		bitsPerSample:   16,
	},
	{
		name:             "spike.ogg",
		title:            "Spike Song (feat. Test)",
		artist:           "Spike Artist One",
		artists:          []string{"Spike Artist One", "Spike Artist Two"},
		album:            "Spike Album",
		albumArtist:      "Spike Album Artist",
		albumArtists:     []string{"Spike Album Artist"},
		trackNo:          3,
		trackTotal:       12,
		discNo:           1,
		discTotal:        2,
		year:             2021,
		date:             "2021-05-04",
		genres:           []string{"Jazz", "Fusion"},
		composers:        []string{"Spike Composer One", "Spike Composer Two"},
		producers:        []string{"Spike Producer"},
		labels:           []string{"Spike Label"},
		releaseType:      "soundtrack",
		comment:          "Spike comment text",
		bpm:              128,
		mbidRecording:    "11111111-2222-3333-4444-555555555555",
		mbidRelease:      "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
		mbidReleaseGroup: "dddddddd-1111-2222-3333-444444444444",
		mbidAlbumArtist:  "cccccccc-1111-2222-3333-444444444444",
		mbidArtistIDs: []string{
			"aaaaaaaa-1111-2222-3333-444444444444",
			"bbbbbbbb-1111-2222-3333-444444444444",
		},
		barcode:         "1234567890123",
		asin:            "B0C0SPIKE0",
		isrcs:           []string{"USS1O210001"},
		replayGainTrack: -7.03,
		replayGainAlbum: -6.51,
		explicit:        boolPtr(true),
		lyrics:          "Plain lyrics line one\nPlain lyrics line two",
		syncedLyrics:    spikeSynced,
		hasCoverArt:     true,
		pictureMime:     "image/png",
		pictureSize:     70,
		// NOTE: the corpus ogg is hand-built synthetic audio (S1 §2); its gold
		// properties (duration 3 s, nominal bitrate 128 kbps) reflect the
		// generator's declared values, which is what S1 signed off on.
		duration:   3,
		bitrate:    128000,
		sampleRate: 44100,
		channels:   2,
	},
	{
		name:             "spike.m4a",
		title:            "Spike Song (feat. Test)",
		artist:           "Spike Artist One",
		artists:          []string{"Spike Artist One", "Spike Artist Two"},
		album:            "Spike Album",
		albumArtist:      "Spike Album Artist",
		albumArtists:     []string{"Spike Album Artist"},
		trackNo:          3,
		trackTotal:       12,
		discNo:           1,
		discTotal:        2,
		year:             2021,
		date:             "2021-05-04",
		genres:           []string{"Jazz", "Fusion"},
		composers:        []string{"Spike Composer One", "Spike Composer Two"},
		producers:        []string{"Spike Producer"},
		labels:           []string{"Spike Label"},
		releaseType:      "soundtrack",
		comment:          "Spike comment text",
		bpm:              128, // W2: tmpo read as 2-byte int
		mbidRecording:    "11111111-2222-3333-4444-555555555555",
		mbidRelease:      "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
		mbidReleaseGroup: "dddddddd-1111-2222-3333-444444444444",
		mbidAlbumArtist:  "cccccccc-1111-2222-3333-444444444444",
		mbidArtistIDs: []string{
			"aaaaaaaa-1111-2222-3333-444444444444",
			"bbbbbbbb-1111-2222-3333-444444444444",
		},
		barcode:         "1234567890123",
		asin:            "B0C0SPIKE0",
		isrcs:           []string{"USS1O210001"},
		replayGainTrack: -7.03,
		replayGainAlbum: -6.51,
		explicit:        boolPtr(true), // W2: rtng atom
		compilation:     boolPtr(true), // cpil
		lyrics:          "Plain lyrics line one\nPlain lyrics line two",
		syncedLyrics:    spikeSynced,
		hasCoverArt:     true,
		pictureMime:     "image/png",
		pictureSize:     70,
		// S1 §5 W5: gold format.bitrate is 800 — music-metadata derives mp4
		// bitrate from the stsz sample table, not the esds avgBitrate.
		// P10 parity: the reader sums stsz exactly like mm (see
		// TestPropertiesParity), so gold's 800 is asserted here too.
		duration:      3,
		bitrate:       800,
		sampleRate:    44100,
		channels:      2,
		bitsPerSample: 16,
	},
	{
		// Pathological ID3v1-only file: Latin-1 high bytes (W4 shim test).
		// gold_v1.json native values: title "Café naïve", artist
		// "Björk \x86 stray ÿ", album "Séance", comment "Comment with é
		// accent", year "1999", genre "Pop".
		name:       "pathological-id3v1.mp3",
		title:      "Café naïve",
		artist:     "Björk \u0086 stray ÿ",
		artists:    []string{"Björk \u0086 stray ÿ"},
		album:      "Séance",
		year:       1999,
		date:       "1999",
		genres:     []string{"Pop"},
		comment:    "Comment with é accent",
		duration:   3.1346938775510202,
		bitrate:    128000,
		sampleRate: 44100,
		channels:   2,
	},
}

func boolPtr(b bool) *bool { return &b }

func TestReadMetadataParity(t *testing.T) {
	for _, tc := range spikeFiles {
		t.Run(tc.name, func(t *testing.T) {
			md, err := ReadMetadata(filepath.Join("testdata", "corpus", tc.name))
			if err != nil {
				t.Fatalf("ReadMetadata: %v", err)
			}

			eqStr := func(field, got, want string) {
				t.Helper()
				if got != want {
					t.Errorf("%s = %q, want %q", field, got, want)
				}
			}
			eqInt := func(field string, got, want int) {
				t.Helper()
				if got != want {
					t.Errorf("%s = %d, want %d", field, got, want)
				}
			}
			eqSlice := func(field string, got, want []string) {
				t.Helper()
				if len(got) == 0 && len(want) == 0 {
					return
				}
				if len(got) != len(want) {
					t.Errorf("%s = %v, want %v", field, got, want)
					return
				}
				for i := range got {
					if got[i] != want[i] {
						t.Errorf("%s = %v, want %v", field, got, want)
						return
					}
				}
			}

			eqStr("Title", md.Title, tc.title)
			eqStr("Artist", md.Artist, tc.artist)
			eqSlice("Artists", md.Artists, tc.artists)
			eqStr("Album", md.Album, tc.album)
			eqStr("AlbumArtist", md.AlbumArtist, tc.albumArtist)
			eqSlice("AlbumArtists", md.AlbumArtists, tc.albumArtists)
			eqInt("TrackNo", md.TrackNo, tc.trackNo)
			eqInt("TrackTotal", md.TrackTotal, tc.trackTotal)
			eqInt("DiscNo", md.DiscNo, tc.discNo)
			eqInt("DiscTotal", md.DiscTotal, tc.discTotal)
			eqInt("Year", md.Year, tc.year)
			eqStr("Date", md.Date, tc.date)
			eqSlice("Genres", md.Genres, tc.genres)
			eqSlice("Composers", md.Composers, tc.composers)
			eqSlice("Producers", md.Producers, tc.producers)
			eqSlice("Labels", md.Labels, tc.labels)
			eqStr("ReleaseType", md.ReleaseType, tc.releaseType)
			eqStr("Comment", md.Comment, tc.comment)
			eqInt("BPM", md.BPM, tc.bpm)
			eqStr("MBIDRecording", md.MBIDRecording, tc.mbidRecording)
			eqStr("MBIDRelease", md.MBIDRelease, tc.mbidRelease)
			eqStr("MBIDReleaseGroup", md.MBIDReleaseGroup, tc.mbidReleaseGroup)
			eqStr("MBIDAlbumArtist", md.MBIDAlbumArtist, tc.mbidAlbumArtist)
			eqSlice("MBIDArtistIDs", md.MBIDArtistIDs, tc.mbidArtistIDs)
			eqStr("Barcode", md.Barcode, tc.barcode)
			eqStr("ASIN", md.ASIN, tc.asin)
			eqSlice("ISRCs", md.ISRCs, tc.isrcs)
			if math.Abs(md.ReplayGainTrack-tc.replayGainTrack) > 1e-9 {
				t.Errorf("ReplayGainTrack = %v, want %v", md.ReplayGainTrack, tc.replayGainTrack)
			}
			if math.Abs(md.ReplayGainAlbum-tc.replayGainAlbum) > 1e-9 {
				t.Errorf("ReplayGainAlbum = %v, want %v", md.ReplayGainAlbum, tc.replayGainAlbum)
			}
			if (md.Explicit == nil) != (tc.explicit == nil) || (md.Explicit != nil && *md.Explicit != *tc.explicit) {
				t.Errorf("Explicit = %v, want %v", md.Explicit, tc.explicit)
			}
			if (md.Compilation == nil) != (tc.compilation == nil) || (md.Compilation != nil && *md.Compilation != *tc.compilation) {
				t.Errorf("Compilation = %v, want %v", md.Compilation, tc.compilation)
			}
			eqStr("Lyrics", md.Lyrics, tc.lyrics)

			if len(md.SyncedLyrics) != len(tc.syncedLyrics) {
				t.Errorf("SyncedLyrics = %v, want %v", md.SyncedLyrics, tc.syncedLyrics)
			} else {
				for i := range md.SyncedLyrics {
					if md.SyncedLyrics[i] != tc.syncedLyrics[i] {
						t.Errorf("SyncedLyrics[%d] = %+v, want %+v", i, md.SyncedLyrics[i], tc.syncedLyrics[i])
					}
				}
			}

			if md.HasCoverArt != tc.hasCoverArt {
				t.Errorf("HasCoverArt = %v, want %v", md.HasCoverArt, tc.hasCoverArt)
			}
			if tc.hasCoverArt {
				if md.Picture == nil {
					t.Fatal("Picture is nil, want cover art")
				}
				eqStr("Picture.MIMEType", md.Picture.MIMEType, tc.pictureMime)
				eqInt("len(Picture.Data)", len(md.Picture.Data), tc.pictureSize)
			} else if md.Picture != nil {
				t.Errorf("Picture = %+v, want nil", md.Picture)
			}
		})
	}
}

// TestPathologicalID3v1Latin1 pins the W4 shim against the exact gold_v1.json
// strings (which carry the U+0086 control byte from the source Latin-1).
func TestPathologicalID3v1Latin1(t *testing.T) {
	md, err := ReadMetadata(filepath.Join("testdata", "corpus", "pathological-id3v1.mp3"))
	if err != nil {
		t.Fatalf("ReadMetadata: %v", err)
	}
	wantTitle := "Café naïve"
	wantArtist := "Björk \u0086 stray ÿ" // gold: "Björk \x86 stray ÿ"
	if md.Title != wantTitle {
		t.Errorf("Title = %q, want %q", md.Title, wantTitle)
	}
	if md.Artist != wantArtist {
		t.Errorf("Artist = %q, want %q", md.Artist, wantArtist)
	}
	if len(md.Artists) != 1 || md.Artists[0] != wantArtist {
		t.Errorf("Artists = %q, want [%q]", md.Artists, wantArtist)
	}
	if md.Album != "Séance" {
		t.Errorf("Album = %q, want %q", md.Album, "Séance")
	}
	if md.Comment != "Comment with é accent" {
		t.Errorf("Comment = %q, want %q", md.Comment, "Comment with é accent")
	}
}

// TestUnitDecodeID3v1Latin1 unit-tests the 5-line shim directly.
func TestUnitDecodeID3v1Latin1(t *testing.T) {
	cases := []struct {
		in, want string
	}{
		{"Caf\xe9 na\xefve", "Café naïve"},
		{"Bj\xf6rk \x86 stray \xff", "Björk \u0086 stray ÿ"},
		{"already utf-8 é", "already utf-8 é"}, // valid UTF-8 passes through
		{"plain ASCII", "plain ASCII"},
	}
	for _, c := range cases {
		if got := decodeID3v1Latin1(c.in); got != c.want {
			t.Errorf("decodeID3v1Latin1(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestParseLrc(t *testing.T) {
	got := parseLrc("[00:00.00]Synced line one\n[00:01.50]Synced line two\n")
	want := spikeSynced
	if len(got) != len(want) {
		t.Fatalf("parseLrc = %v, want %v", got, want)
	}
	for i := range got {
		if got[i] != want[i] {
			t.Errorf("parseLrc[%d] = %+v, want %+v", i, got[i], want[i])
		}
	}
}
