package testdualrun

// P10b report: writes docs/v2-p10b-dualrun-report.md with the measured
// numbers, the catalog count-diff table, the serving-verification matrix,
// the cutover runbook, and the rollback story.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// correctionHeader20260925 is the CORRECTION block committed after the
// wrong-path run of 2026-09-25 (the harness pointed at the compose fallback
// directory, 20 files, and concluded the catalog was stale — a path
// artifact). It is preserved verbatim at the top of every regenerated
// report, with an explicit SUPERSEDED status line; the measured sections
// below it always come from the latest (corrected) run.
var correctionHeader20260925 = "> **CORRECTION (2026-09-26):** the library path used for this run was\n" +
	"> WRONG. `config/sonarly/library` (20 files) is the compose *fallback*\n" +
	"> used when `LIBRARY_MUSIC` is unset; the real library per `.env` is\n" +
	"> `/srv/dev-disk-by-uuid-2e9226ea-.../resources/Música` (238 GB, 7,421\n" +
	"> files — exactly matching the catalog's 7,421 active songs pointing at\n" +
	"> `/media/music/...`, the in-container mount of that disk). The\n" +
	"> \"stale catalog / 7,401 deactivations\" conclusion was an artifact of\n" +
	"> pointing v2 at the fallback directory, NOT a property of the\n" +
	"> production data. The catalog is healthy. A corrected dual-run against\n" +
	"> the real path superseded this report (see its regeneration below /\n" +
	"> follow-up commit). No files were deleted by anyone: v2 is read-only\n" +
	"> toward the library and ran against DB copies only.\n" +
	">\n" +
	"> **Status: SUPERSEDED by the corrected run below (2026-09-26).** The\n" +
	"> text above is kept verbatim for the record; every measured section\n" +
	"> underneath is from the corrected run against the real library path."

func finalizeReport(testCode int, total time.Duration) {
	now := time.Now().Format("2006-01-02 15:04:05 MST")
	var sb strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&sb, format+"\n", args...) }

	status := "PASS"
	if testCode != 0 || streamMismatches > 0 {
		status = "FAIL"
	}

	w("%s", correctionHeader20260925)
	w("")
	w("# Sonarly v2 — P10b Production Dual-Run Report — Corrected run 2026-09-26")
	w("")
	w("_Generated by `go test ./testdualrun/` on %s. This file is regenerated on every dual-run; do not hand-edit the measured sections._", now)
	w("")
	w("- **Overall result: %s** (go test exit code %d, stream hash mismatches: %d — a mismatch is a release blocker)", status, testCode, streamMismatches)
	w("- Harness: `v2/testdualrun` — production DB snapshot (main + WAL + SHM) into a scratch dir, v2 booted on one copy against the **real** library directory (read-only), second copy kept pristine for the catalog diff.")
	w("- Library path this run: `%s` — verified against `.env` `LIBRARY_MUSIC` (NOT the compose fallback directory that invalided the 2026-09-25 run).", env.libDir)
	w("- The live v1 container was not stopped, restarted, or written to at any point.")
	w("")
	w("## Environment and snapshot")
	w("")
	for _, line := range env.setupLog {
		w("- %s", line)
	}
	w("- Snapshot copied from live: db %s, wal %s", humanBytes(env.snapDB), humanBytes(env.snapWAL))
	w("- Library: `%s` — %d audio files, %s", env.libDir, len(env.onDisk), humanBytes(totalLibraryBytes()))
	w("- Baseline catalog (pristine copy, post-WAL-recovery, `PRAGMA quick_check` = ok):")
	w("")
	w("| table | rows |")
	w("|---|---|")
	for _, t := range countTables {
		w("| %s | %d |", t, env.baseline.Counts[t])
	}
	w("")

	fastPath := env.scan.Stats.Added == 0 && env.scan.Stats.Removed == 0 && env.scan.Stats.Moved == 0
	if reconMissing > 0 {
		w("### Finding: the pre-scan active catalog is stale relative to the library directory")
		w("")
		w("Of **%d pre-scan active songs**, **%d files are missing** on disk. The boot scan therefore performs a reconciliation (deactivating rows whose files are gone); **v1's next successful scan would do exactly the same** — this is v1-parity behavior, not a v2 divergence.", env.baseline.Active, reconMissing)
		w("")
	} else if fastPath {
		w("### Finding: none — the catalog describes the library on disk exactly (mtime fast path applies)")
		w("")
		w("Pre-scan active=**%d** and the library directory holds **%d audio files (%s)**: every active row's file exists on disk (missing=0, present=%d). The boot scan is a stat-only pass over the whole library: v2's v1-parity mtime fast path (`existing.active && existing.mtime == file mtime`) skips the metadata read AND the checksum hash for unchanged files, so the expected stats are added=0, updated=0, removed=0, failed=0 at seconds-scale wall time. Any large `updated` count below would mean mtimes diverge from the catalog and is flagged for investigation.", env.baseline.Active, len(env.onDisk), humanBytes(totalLibraryBytes()), reconPresent)
		w("")
	} else {
		w("### Finding: the boot scan changed the catalog")
		w("")
		w("added=%d removed=%d moved=%d — see the diff below for the per-row classification.", env.scan.Stats.Added, env.scan.Stats.Removed, env.scan.Stats.Moved)
		w("")
	}

	if fastPath {
		w("## Boot scan — mtime fast path (no reconciliation needed)")
	} else {
		w("## Reconciliation run")
	}
	w("")
	for _, line := range reconFacts {
		w("- %s", line)
	}
	w("")
	w("## Catalog diff (v2-processed copy vs. pristine snapshot copy)")
	w("")
	w("Row counts plus per-row SHA-256 over canonical projections (volatile scan-refresh columns `songs.mtime`/`songs.checksum` excluded from the strict hash but compared and reported). Full per-row key lists were written to `%s/<table>.txt` in the scratch dir (keep the scratch dir with P10B_KEEP_TMP=1 to inspect them).", diffArtifacts)
	w("")
	w("| table | pristine | v2 | added | removed | changed | verdict |")
	w("|---|---|---|---|---|---|---|")
	for _, td := range diffResults {
		verdict := "identical"
		if len(td.Added)+len(td.Removed)+len(td.Changed) > 0 {
			verdict = td.Summary
			if !td.OK {
				verdict = "FINDINGS: " + strings.Join(td.Findings, "; ")
			}
		}
		w("| %s | %d | %d | %d | %d | %d | %s |", td.Name, td.CountA, td.CountB, len(td.Added), len(td.Removed), len(td.Changed), verdict)
	}
	w("")
	for _, td := range diffResults {
		if td.OK && len(td.Added)+len(td.Removed)+len(td.Changed) == 0 {
			continue
		}
		w("### diff detail: %s", td.Name)
		w("")
		if td.Summary != "" {
			w("- %s", td.Summary)
		}
		if len(td.Findings) > 0 {
			w("- **FINDINGS:**")
			for _, f := range td.Findings {
				w("  - %s", f)
			}
		}
		w("- samples: added=%v removed=%v changed=%v", sample(td.Added), sample(td.Removed), sample(td.Changed))
		w("")
	}
	w("Diff wall time: %s.", diffDuration.Round(time.Millisecond))
	w("")
	w("## Serving verification on real data (native API)")
	w("")
	for _, line := range servingFacts {
		w("- %s", line)
	}
	w("")
	w("| song | fmt | detail | stream sha256 == file | range 0-65535 | cover |")
	w("|---|---|---|---|---|---|")
	for _, r := range results {
		stream := "MISMATCH **RELEASE BLOCKER**"
		if !r.StreamMismatch && r.StreamSHA != "" {
			stream = fmt.Sprintf("match (%s…)", r.StreamSHA[:12])
		}
		rng := fmt.Sprintf("status %d", r.RangeStatus)
		if r.RangeOK {
			rng = "206, bytes match"
		}
		cover := "n/a"
		if r.CoverSHA != "" {
			cover = fmt.Sprintf("%d bytes (%s…)", r.CoverBytes, r.CoverSHA[:12])
		}
		w("| %s | %s | %s | %s | %s | %s |", r.Pick.Title, r.Pick.Ext, r.APIDetail, stream, rng, cover)
	}
	w("")
	w("## Serving verification (OpenSubsonic /rest, u/t/s token auth)")
	w("")
	w("| song | stream.view sha256 == file | getCoverArt == /api/cover-art |")
	w("|---|---|---|")
	for _, r := range results {
		rest := "not run"
		if r.RestStream != "" {
			rest = "MISMATCH **RELEASE BLOCKER**"
			if !r.StreamMismatch {
				rest = fmt.Sprintf("match (%s…)", r.RestStream[:12])
			}
		}
		cov := "n/a"
		if r.CoverSHA != "" {
			cov = "match"
			if !r.RestCoverOK {
				cov = "MISMATCH"
			}
		}
		w("| %s | %s | %s |", r.Pick.Title, rest, cov)
	}
	w("")
	w("## Transcode smoke")
	w("")
	for _, line := range transcodeFacts {
		w("- %s", line)
	}
	w("")
	w("## Library read-only proof")
	w("")
	for _, line := range libUntouched {
		w("- %s", line)
	}
	w("")
	w("## Live v1 during the dual-run")
	w("")
	for _, line := range env.setupLog {
		if strings.HasPrefix(line, "live v1 probe:") {
			w("- %s", line)
		}
	}
	w("")
	w("Response-level parity evidence is the P10 testparity suite (94/94, see `docs/v2-p10-parity-report.md`). No login or state-changing call was attempted against v1.")
	w("")

	// Static sections. « is a backtick placeholder and §…§ are measured-value
	// placeholders (raw strings cannot hold backticks); unmasked at write time.
	staticSection := `## Cutover runbook

1. **Backup (rollback anchor).** Stop the sonarly container, then copy the
   whole data directory: «cp -a config/sonarly/data config/sonarly/data.bak-pre-v2-$(date +%Y%m%d)»
   (the DB is in WAL mode — copy «sonarly.db» **and** «sonarly.db-wal»; do
   not delete the -wal). Verify the copy with «PRAGMA quick_check».
2. **Image/env swap.** Point the compose service at the v2 image and adjust
   env names: «SONARLY_DB_PATH=/data/db/sonarly.db»,
   «SONARLY_DATA_DIR=/data/db», «SONARLY_LIBRARY_PATH=/media/music»,
   «SONARLY_INGEST_PATH=/data/ingest», keep «SESSION_SECRET» **identical**
   (it seals users.subsonic_password_encrypted and signs sessions), and set
   the interval knobs to the v1 cadence («SONARLY_SCAN_INTERVAL_MINUTES=60»,
   «SONARLY_WATCH_POLL_INTERVAL=5» if polling, «SONARLY_ARTIST_IMAGE_INTERVAL_MINUTES=1440»,
   «SONARLY_INGEST_INTERVAL_MINUTES=60»). Same volume mounts; v2 keeps the
   DB schema additive-compatible, so no DB export/import step exists.
   «SONARLY_LIBRARY_PATH» must be the REAL library («LIBRARY_MUSIC» in
   «.env») — the 2026-09-25 run proved that pointing at the compose fallback
   directory produces a bogus mass-reconciliation; see the superseded
   correction header above.
3. **Boot.** The container runs v2's migrations (no-op baseline + nullable
   scan_jobs columns + FTS5 tables) and pushes one initial scan.
   Expect the stat-only mtime fast path measured in the corrected run:
   added=0 removed=0 failed=0 in §SCANWALL§ wall time over
   §SCANFILES§ files (§SCANBYTES§); «updated» counts only the files that
   changed since v1's last scan (1 file in the corrected run). Files
   genuinely added or modified get imported; files vanished from disk get
   deactivated, which is exactly what v1's next scan would do.
4. **Verify.**
   «curl -fsS localhost:<port>/health» → 200; log in through the web UI;
   play one song start-to-finish in a Subsonic client; confirm
   «GET /api/scans/status» reaches completed with failed=0; eyeball the
   library counts against expectation.
5. **Done.** Keep the pre-v2 backup until v2 has soaked (recommend ≥1 week).

## Rollback procedure

1. Stop the v2 container.
2. Restore the DB: «cp -a config/sonarly/data.bak-pre-v2-*/sonarly.db* config/sonarly/data/»
   (main + -wal + -shm from the backup; SQLite replays the WAL on open).
   Any data written while v2 was live — scrobbles, ratings, new playlists —
   survives only if it predates the backup; state created after the backup
   is lost on rollback. Plan the soak window with that in mind (or take a
   fresh backup just before deciding to stay).
3. Swap the image/env back to v1 («ghcr.io/miquelrosell99/sonarly:latest»,
   v1 env names) and start. v1 opens the restored DB with its own migrator.
4. Verify «GET /healthz» → 200, log in, play one song.

### Compatibility analysis (what v2 writes that v1 must tolerate)

Measured across both dual-runs, v2's only schema footprints over the v1
schema are:

- «schema_migrations» ledger rows (0001–0003) — a NEW table v1 never
  reads. Inert under v1.
- «scan_jobs.payload» and «scan_jobs.created_at» — **nullable** ADD
  COLUMNs (migration 0002). v1's scan_jobs inserts name explicit columns,
  so they succeed and the new columns stay NULL; v1's reads select its own
  columns. Inert.
- «songs_fts»/«albums_fts»/«artists_fts» FTS5 virtual tables
  (migration 0003) — new tables v1 never touches. Inert.
- Deactivation scoping delta (surfaced by the first, pre-rebase dual-run
  pass): v1's scanner deactivates every DB path not seen this scan except
  paths under a FAILED root; v2's scanner («internal/modules/library»
  deactivateMissing) additionally skips paths under no walked library root —
  a deliberate hardening so a library-scoped scan cannot touch another
  library's rows. With the standard deployment (one library root, DB paths
  rooted under it) the behaviors are identical; the delta only surfaces
  when the DB holds paths outside every configured library root (e.g.
  after re-rooting the library without rewriting songs.file_path). In that
  situation v1 mass-deactivates the out-of-root catalog while v2 preserves
  it. Flagged here as a known, deliberate deviation — decide before cutover
  whether to port v1's behavior or accept the hardening.
- Re-persist normalizations (documented envelope; **7,420 of 7,421 files
  matched the mtime fast path exactly — the scanner re-persisted only the
  one file whose mtime genuinely changed on disk since v1's last scan**, and
  that row stayed inside the envelope below): «duration»
  fractional seconds -> integer seconds (SPEC-duration-integer-seconds,
  accepted by the P10 parity suite), legacy «" "»-valued «comment» /
  «music_brainz_id» -> NULL, and fractional legacy «bit_rate» -> NULL —
  the last because v2's pure-Go tag reader does not estimate a FLAC
  bitrate where music-metadata did. v1's current scanner would produce
  the same NULLs (its default persist is also full-replace); the
  duration/«bit_rate» response deltas only touch re-persisted legacy rows.

The baseline migration is pure «CREATE TABLE IF NOT EXISTS» over the exact
v1 001–049 shape, so no existing column/type/index is altered. Beyond
schema, v2 writes the same row shapes v1 writes (same tables, same column
semantics) — the catalog diff above shows the only content deltas are the
scan reconciliation (activity flags / provable moves / mtime+checksum
refreshes), which is ordinary v1-visible library state. No v2 row format is
unreadable to v1. (Claim grounded in the additive-migration design and
corroborated by this run's diff; the testparity suite proves the
request-level contract.)

## Deployment runtime dependencies (v2 image)

| dependency | used by | without it |
|---|---|---|
| «ffmpeg» | transcoding («/api/stream?maxBitRate=», Subsonic transcoding) — «internal/modules/playback» | transcode requests fail; direct streams, catalog, search all unaffected |
| «python3» + «mutagen» (pip) | tag editing — «internal/audio» TagWriter (write → organize → resync) | tag-edit endpoints answer 500 "Failed to write tags"; scanning/serving unaffected (metadata reads are pure Go) |

v2 needs no Node runtime. The v1 image already ships both dependencies, so
the existing install layer carries over as-is.
`
	replacer := strings.NewReplacer("«", "`", "»", "`",
		"§SCANWALL§", fmt.Sprintf("%s", env.scan.WallClock.Round(time.Millisecond)),
		"§SCANFILES§", fmt.Sprint(env.scan.Stats.Scanned),
		"§SCANBYTES§", humanBytes(totalLibraryBytes()),
	)
	w("%s", replacer.Replace(staticSection))

	path := filepath.Join("..", "..", "docs", "v2-p10b-dualrun-report.md")
	if err := os.WriteFile(path, []byte(sb.String()), 0o644); err != nil {
		logf("write report: %v", err)
		return
	}
	logf("report written to %s", path)
}

func dbSize(p string) int64 {
	st, err := os.Stat(p)
	if err != nil {
		return -1
	}
	return st.Size()
}

func humanBytes(n int64) string {
	if n < 0 {
		return "n/a"
	}
	const unit = 1024
	if n < unit {
		return fmt.Sprintf("%d B", n)
	}
	div, exp := int64(unit), 0
	for m := n / unit; m >= unit; m /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %ciB", float64(n)/float64(div), "KMGTPE"[exp])
}
