package testdualrun

// P10b report: writes docs/v2-p10b-dualrun-report.md with the measured
// numbers, the catalog count-diff table, the serving-verification matrix,
// the cutover runbook, and the rollback story.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func finalizeReport(testCode int, total time.Duration) {
	now := time.Now().Format("2006-01-02 15:04:05 MST")
	var sb strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&sb, format+"\n", args...) }

	status := "PASS"
	if testCode != 0 || streamMismatches > 0 {
		status = "FAIL"
	}

	w("# Sonarly v2 — P10b Production Dual-Run Report")
	w("")
	w("_Generated by `go test ./testdualrun/` on %s. This file is regenerated on every dual-run; do not hand-edit the measured sections._", now)
	w("")
	w("- **Overall result: %s** (go test exit code %d, stream hash mismatches: %d — a mismatch is a release blocker)", status, testCode, streamMismatches)
	w("- Harness: `v2/testdualrun` — production DB snapshot (main + WAL + SHM) into a scratch dir, v2 booted on one copy against the **real** library directory (read-only), second copy kept pristine for the catalog diff.")
	w("- The live v1 container was not stopped, restarted, or written to at any point.")
	w("")
	w("## Environment and snapshot")
	w("")
	for _, line := range env.setupLog {
		w("- %s", line)
	}
	w("- Snapshot copied from live: db %s, wal %s", humanBytes(env.snapDB), humanBytes(env.snapWAL))
	w("- Library: `%s` — %d audio files, %s", env.libDir, len(env.onDisk), humanBytes(totalLibraryBytes()))
	w("- Baseline catalog (pristine copy, post-WAL-recovery, `PRAGMA quick_check` = ok):")
	w("")
	w("| table | rows |")
	w("|---|---|")
	for _, t := range countTables {
		w("| %s | %d |", t, env.baseline.Counts[t])
	}
	w("")
	w("### Finding: the production DB's active catalog is stale relative to the library directory")
	w("")
	w("The database still lists **%d active songs**, but the library directory on disk contains only **%d audio files (%s)**. The library was replaced by a single album after the last v1 scan, so v1's active catalog no longer describes reality. v2's initial scan therefore performs a large reconciliation (deactivating rows whose files are gone); **v1's next successful scan would do exactly the same** — this is v1-parity behavior, not a v2 divergence. The cutover/rollback sections cover what this means in practice.", env.baseline.Active, len(env.onDisk), humanBytes(totalLibraryBytes()))
	w("")
	w("## Reconciliation run")
	w("")
	for _, line := range reconFacts {
		w("- %s", line)
	}
	w("")
	w("## Catalog diff (v2-processed copy vs. pristine snapshot copy)")
	w("")
	w("Row counts plus per-row SHA-256 over canonical projections (volatile scan-refresh columns `songs.mtime`/`songs.checksum` excluded from the strict hash but compared and reported). Full per-row key lists were written to `%s/<table>.txt` in the scratch dir (keep the scratch dir with P10B_KEEP_TMP=1 to inspect them).", diffArtifacts)
	w("")
	w("| table | pristine | v2 | added | removed | changed | verdict |")
	w("|---|---|---|---|---|---|---|")
	for _, td := range diffResults {
		verdict := "identical"
		if len(td.Added)+len(td.Removed)+len(td.Changed) > 0 {
			verdict = td.Summary
			if !td.OK {
				verdict = "FINDINGS: " + strings.Join(td.Findings, "; ")
			}
		}
		w("| %s | %d | %d | %d | %d | %d | %s |", td.Name, td.CountA, td.CountB, len(td.Added), len(td.Removed), len(td.Changed), verdict)
	}
	w("")
	for _, td := range diffResults {
		if td.OK && len(td.Added)+len(td.Removed)+len(td.Changed) == 0 {
			continue
		}
		w("### diff detail: %s", td.Name)
		w("")
		if td.Summary != "" {
			w("- %s", td.Summary)
		}
		if len(td.Findings) > 0 {
			w("- **FINDINGS:**")
			for _, f := range td.Findings {
				w("  - %s", f)
			}
		}
		w("- samples: added=%v removed=%v changed=%v", sample(td.Added), sample(td.Removed), sample(td.Changed))
		w("")
	}
	w("Diff wall time: %s.", diffDuration.Round(time.Millisecond))
	w("")
	w("## Serving verification on real data (native API)")
	w("")
	for _, line := range servingFacts {
		w("- %s", line)
	}
	w("")
	w("| song | fmt | detail | stream sha256 == file | range 0-65535 | cover |")
	w("|---|---|---|---|---|---|")
	for _, r := range results {
		stream := "MISMATCH **RELEASE BLOCKER**"
		if !r.StreamMismatch && r.StreamSHA != "" {
			stream = fmt.Sprintf("match (%s…)", r.StreamSHA[:12])
		}
		rng := fmt.Sprintf("status %d", r.RangeStatus)
		if r.RangeOK {
			rng = "206, bytes match"
		}
		cover := "n/a"
		if r.CoverSHA != "" {
			cover = fmt.Sprintf("%d bytes (%s…)", r.CoverBytes, r.CoverSHA[:12])
		}
		w("| %s | %s | %s | %s | %s | %s |", r.Pick.Title, r.Pick.Ext, r.APIDetail, stream, rng, cover)
	}
	w("")
	w("## Serving verification (OpenSubsonic /rest, u/t/s token auth)")
	w("")
	w("| song | stream.view sha256 == file | getCoverArt == /api/cover-art |")
	w("|---|---|---|")
	for _, r := range results {
		rest := "not run"
		if r.RestStream != "" {
			rest = "MISMATCH **RELEASE BLOCKER**"
			if !r.StreamMismatch {
				rest = fmt.Sprintf("match (%s…)", r.RestStream[:12])
			}
		}
		cov := "n/a"
		if r.CoverSHA != "" {
			cov = "match"
			if !r.RestCoverOK {
				cov = "MISMATCH"
			}
		}
		w("| %s | %s | %s |", r.Pick.Title, rest, cov)
	}
	w("")
	w("## Transcode smoke")
	w("")
	for _, line := range transcodeFacts {
		w("- %s", line)
	}
	w("")
	w("## Library read-only proof")
	w("")
	for _, line := range libUntouched {
		w("- %s", line)
	}
	w("")
	w("## Live v1 during the dual-run")
	w("")
	for _, line := range env.setupLog {
		if strings.HasPrefix(line, "live v1 probe:") {
			w("- %s", line)
		}
	}
	w("")
	w("Response-level parity evidence is the P10 testparity suite (94/94, see `docs/v2-p10-parity-report.md`). No login or state-changing call was attempted against v1.")
	w("")

	// Static sections. « is a backtick placeholder (raw strings cannot hold
	// backticks); unmasked at write time.
	staticSection := `## Cutover runbook

1. **Backup (rollback anchor).** Stop the sonarly container, then copy the
   whole data directory: «cp -a config/sonarly/data config/sonarly/data.bak-pre-v2-$(date +%Y%m%d)»
   (the DB is in WAL mode — copy «sonarly.db» **and** «sonarly.db-wal»; do
   not delete the -wal). Verify the copy with «PRAGMA quick_check».
2. **Image/env swap.** Point the compose service at the v2 image and adjust
   env names: «SONARLY_DB_PATH=/data/db/sonarly.db»,
   «SONARLY_DATA_DIR=/data/db», «SONARLY_LIBRARY_PATH=/media/music»,
   «SONARLY_INGEST_PATH=/data/ingest», keep «SESSION_SECRET» **identical**
   (it seals users.subsonic_password_encrypted and signs sessions), and set
   the interval knobs to the v1 cadence («SONARLY_SCAN_INTERVAL_MINUTES=60»,
   «SONARLY_WATCH_POLL_INTERVAL=5» if polling, «SONARLY_ARTIST_IMAGE_INTERVAL_MINUTES=1440»,
   «SONARLY_INGEST_INTERVAL_MINUTES=60»). Same volume mounts; v2 keeps the
   DB schema additive-compatible, so no DB export/import step exists.
3. **Boot.** The container runs v2's migrations (no-op baseline + nullable
   scan_jobs columns + FTS5 tables) and pushes one initial scan.
   Expect a reconciliation pass exactly like this report's: any file the old
   catalog claimed but that is not on disk is deactivated (v1 would do the
   same on its next scan).
4. **Verify.**
   «curl -fsS localhost:<port>/health» → 200; log in through the web UI;
   play one song start-to-finish in a Subsonic client; confirm
   «GET /api/scans/status» reaches completed with failed=0; eyeball the
   library counts against expectation.
5. **Done.** Keep the pre-v2 backup until v2 has soaked (recommend ≥1 week).

## Rollback procedure

1. Stop the v2 container.
2. Restore the DB: «cp -a config/sonarly/data.bak-pre-v2-*/sonarly.db* config/sonarly/data/»
   (main + -wal + -shm from the backup; SQLite replays the WAL on open).
   Any data written while v2 was live — scrobbles, ratings, new playlists —
   survives only if it predates the backup; state created after the backup
   is lost on rollback. Plan the soak window with that in mind (or take a
   fresh backup just before deciding to stay).
3. Swap the image/env back to v1 («ghcr.io/miquelrosell99/sonarly:latest»,
   v1 env names) and start. v1 opens the restored DB with its own migrator.
4. Verify «GET /healthz» → 200, log in, play one song.

### Compatibility analysis (what v2 writes that v1 must tolerate)

Measured on this run, v2's only schema footprints over the v1 schema are:

- «schema_migrations» ledger rows (0001–0003) — a NEW table v1 never
  reads. Inert under v1.
- «scan_jobs.payload» and «scan_jobs.created_at» — **nullable** ADD
  COLUMNs (migration 0002). v1's scan_jobs inserts name explicit columns,
  so they succeed and the new columns stay NULL; v1's reads select its own
  columns. Inert.
- «songs_fts»/«albums_fts»/«artists_fts» FTS5 virtual tables
  (migration 0003) — new tables v1 never touches. Inert.
- Deactivation scoping delta (surfaced by the first, pre-rebase dual-run
  pass): v1's scanner deactivates every DB path not seen this scan except
  paths under a FAILED root; v2's scanner («internal/modules/library»
  deactivateMissing) additionally skips paths under no walked library root —
  a deliberate hardening so a library-scoped scan cannot touch another
  library's rows. With the standard deployment (one library root, DB paths
  rooted under it) the behaviors are identical; the delta only surfaces
  when the DB holds paths outside every configured library root (e.g.
  after re-rooting the library without rewriting songs.file_path). In that
  situation v1 mass-deactivates the out-of-root catalog while v2 preserves
  it. Flagged here as a known, deliberate deviation — decide before cutover
  whether to port v1's behavior or accept the hardening.
- Re-persist normalizations observed on the 20 legacy rows this scan
  refreshed (all within the accepted parity envelope): «duration»
  fractional seconds -> integer seconds (SPEC-duration-integer-seconds,
  accepted by the P10 parity suite), legacy «" "»-valued «comment» /
  «music_brainz_id» -> NULL, and fractional legacy «bit_rate» -> NULL —
  the last because v2's pure-Go tag reader does not estimate a FLAC
  bitrate where music-metadata did. v1's current scanner would produce
  the same NULLs (its default persist is also full-replace); the
  duration/«bit_rate» response deltas only touch re-persisted legacy rows.

The baseline migration is pure «CREATE TABLE IF NOT EXISTS» over the exact
v1 001–049 shape, so no existing column/type/index is altered. Beyond
schema, v2 writes the same row shapes v1 writes (same tables, same column
semantics) — the catalog diff above shows the only content deltas are the
scan reconciliation (activity flags / provable moves / mtime+checksum
refreshes), which is ordinary v1-visible library state. No v2 row format is
unreadable to v1. (Claim grounded in the additive-migration design and
corroborated by this run's diff; the testparity suite proves the
request-level contract.)

## Deployment runtime dependencies (v2 image)

| dependency | used by | without it |
|---|---|---|
| «ffmpeg» | transcoding («/api/stream?maxBitRate=», Subsonic transcoding) — «internal/modules/playback» | transcode requests fail; direct streams, catalog, search all unaffected |
| «python3» + «mutagen» (pip) | tag editing — «internal/audio» TagWriter (write → organize → resync) | tag-edit endpoints answer 500 "Failed to write tags"; scanning/serving unaffected (metadata reads are pure Go) |

v2 needs no Node runtime. The v1 image already ships both dependencies, so
the existing install layer carries over as-is.
`
	w("%s", strings.NewReplacer("«", "`", "»", "`").Replace(staticSection))

	path := filepath.Join("..", "..", "docs", "v2-p10b-dualrun-report.md")
	if err := os.WriteFile(path, []byte(sb.String()), 0o644); err != nil {
		logf("write report: %v", err)
		return
	}
	logf("report written to %s", path)
}

func dbSize(p string) int64 {
	st, err := os.Stat(p)
	if err != nil {
		return -1
	}
	return st.Size()
}

func humanBytes(n int64) string {
	if n < 0 {
		return "n/a"
	}
	const unit = 1024
	if n < unit {
		return fmt.Sprintf("%d B", n)
	}
	div, exp := int64(unit), 0
	for m := n / unit; m >= unit; m /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %ciB", float64(n)/float64(div), "KMGTPE"[exp])
}
