ALTER TABLE users ADD COLUMN hide_explicit INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN blur_explicit_titles INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN blur_explicit_covers INTEGER NOT NULL DEFAULT 0;
